{% set name = "sicor" %}
{% set version = "0.14.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sicor-{{ version }}.tar.gz
  sha256: 654a1f99e3ee197ea2abaa3d77402a3d773994415d8958b4e8827b99ff9f4b03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-git
    - gdal
    - pytables
    - h5py
    - numba
    - llvmlite
    - pyfftw
    - pygrib
    - scikit-learn
  run:
    - arosics
    - cerberus
    - dicttoxml
    - dill
    - gdal
    - geoarray
    - glymur
    - h5py
    - iso8601
    - jsmin
    - llvmlite
    - matplotlib-base
    - mpld3
    - netcdf4
    - numba
    - numpy
    - pandas
    - pillow
    - pint
    - psutil
    - pyprind
    - pyproj
    - pyrsr
    - pytables
    - python >=3.6
    - scikit-image
    - scikit-learn
    - scipy
    - sympy
    - tqdm

test:
  imports:
    - sicor
    - sicor.AC.RtFo
    - sicor.AC.RtFo_3_phases
    - sicor.ECMWF
    - sicor.Mask
    - sicor.tables
    - sicor.Tools
    - sicor.sicor
    - sicor.sicor_ac
    - sicor.sicor_enmap
  # commands:
    # - pip check  # disabled as sicor requirements contain test and docs requirements that are not installed with the conda-forge package
  # requires:
    # - pip

about:
  home: https://gitext.gfz-potsdam.de/EnMAP/sicor
  summary: Sensor Independent Atmospheric Correction
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklasbohn
    - danschef
