{% set name = "sicor" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sicor-{{ version }}.tar.gz
  sha256: 1cae64aa018e9433c8c3e211efa202e5be018cc41cdaeb1815c3c6227b0f7f2b


build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-git
  run:
    - arosics >=1.2.4
    - cachetools
    - cdsapi
    - cerberus
    - dicttoxml
    - dill
    - ecmwf-api-client
    - gdal
    - gdown
    - geoarray
    - glymur
    - h5py
    - iso8601
    - jsmin
    - matplotlib-base
    - mpld3
    - netcdf4
    - numba
    - numpy
    - openpyxl
    - pandas
    - pillow
    - pint
    - psutil
    - pygrib
    - pyprind
    - pyproj
    - pyrsr
    - pytables
    - python >=3.8
    - py-tools-ds
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - sympy
    - tqdm

test:
  imports:
    - sicor
    - sicor.AC.RtFo
    - sicor.AC.RtFo_3_phases
    - sicor.ECMWF
    - sicor.Mask
    - sicor.tables
    - sicor.Tools
    - sicor.sicor
    - sicor.sicor_ac
    - sicor.sicor_enmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitext.gfz-potsdam.de/EnMAP/sicor
  summary: Sensor Independent Atmospheric Correction
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklasbohn
    - danschef
