{% set name = "sicor" %}
{% set version = "0.14.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sicor-{{ version }}.tar.gz
  sha256: b600efe3e92e1a5b958424a78249b5fe9418f2574b0c7ac1ae8e5cbcfe0e3df2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-git
    - gdal
    - pytables
    - h5py
    - numba
    - pyfftw
    - pygrib
    - scikit-learn
  run:
    - arosics
    - cachetools
    - cerberus
    - dicttoxml
    - dill
    - ecmwf-api-client
    - gdal
    - geoarray
    - glymur
    - h5py
    - iso8601
    - jsmin
    - matplotlib-base
    - mpld3
    - netcdf4
    - numba
    - numpy
    - pandas
    - pillow
    - pint
    - psutil
    - pygrib
    - pyprind
    - pyproj
    - pyrsr
    - pytables
    - python >=3.6
    - py-tools-ds
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - sympy
    - tqdm

test:
  imports:
    - sicor
    - sicor.AC.RtFo
    - sicor.AC.RtFo_3_phases
    - sicor.ECMWF
    - sicor.Mask
    - sicor.tables
    - sicor.Tools
    - sicor.sicor
    - sicor.sicor_ac
    - sicor.sicor_enmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitext.gfz-potsdam.de/EnMAP/sicor
  summary: Sensor Independent Atmospheric Correction
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklasbohn
    - danschef
